name: 'PMD Source Code Analyzer Action'
author: Girish (forked from sfdx-actions/setup-pmd)
description: 'This action allows to use PMD Source Code Analyzer from GitHub Actions'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'red'
